services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Newspage\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  B13\Newspage\Filter\CategoryFilter:
    public: true
  B13\Newspage\Filter\CategoriesFilter:
    public: true

  B13\Newspage\EventListener\SimplePaginationProvider:
    tags:
      - name: event.listener
        identifier: 'ext-newspage-simplePaginationProvider'
        event: B13\Newspage\Event\CreatingPaginationEvent

  B13\Newspage\EventListener\NewsLayoutListener:
    tags:
      - name: event.listener
        identifier: 'ext-newspage-newsLayoutListener'
